- README.md
- game.ini
- params.ini
- release.py
- src/bot.py
- src/char/hammerdin.py
- src/char/i_char.py
- src/char/sorceress.py
- src/config.py
- src/death_manager.py
- src/npc_manager.py
- src/pather.py
- src/ui_manager.py
- more random click positions
- more random delays
- some shortening of delays. ppl were complaining about too long runs. next they will complain again getting stuck I guess...
- remove unused skill
- moved static pathes to param file
> randomness and delays

- README.md
- params.ini
- src/char/sorceress.py
- src/config.py
> Add thunderstorm to possible pre-buffs

- src/template_finder.py
- src/ui_manager.py
This case is expected to timeout sometimes and search again. Dont want to have a new screenshot every time.
> Dont take ss when searching for exit

- src/ui_manager.py
guess commit message is enough :)
> actually stashing gold (wasnt implemented yet)

- README.md
- params.ini
- src/bot.py
- src/config.py
- src/game_recovery.py
- src/run.py
- After max game length is done. Kill bot thread (and all its threads and make sure there is no endless loop calling new functions). Then attempt to get back to start screen: 3 possible situations:
1) We are already there
2) We are dead
3) We are ingame. We might be in some menu, by pressing esc often enough we should at some point end up  with a "save and exit" btn
- Also adding a pause function (which some delay as it waits for the next state change)
> Recover from being stuck

- game.ini
- src/bot.py
- src/char/i_char.py
- src/char/sorceress.py
- src/ui_manager.py
- Will check if town portal failed and refresh tomb on next game
- Make sure weapon switch was successful and we are back to main weapon
> Detect no more tps and check weapon switch

- README.md
Alternatively, could replace all occurrences of botty and change to booty.
> ( ͡° ͜ʖ ͡°)

- params.ini
- src/char/sorceress.py
- src/config.py
- src/template_finder.py
Also, decrease thresholds from template matching and make it configurable.
Fixes #74
> Fix eld fallback

- README.md
- params.ini
- src/config.py
- src/pickit.py
- src/ui_manager.py
Reopening this PR since I'm not sure if #42 is going to be merged or not. (I couldn't reopen the existing PR since I force pushed due to rebase)
The changes in this PR are pretty small and are useful to my runs. (Never getting only hp-pots or only mana-pots)
> Allow to control desired hp/mp column

- src/bot.py
Fixed the small typo that caused:
```
Exception has occurred: NameError
name 'bot' is not defined
```
> Small typo fixed.

- src/game_recovery.py
- src/run.py
- src/ui_manager.py
Two issues:
- The esc was doing a press instead of a send (press and release). Thus if it did not work the first time, the retry will fail
- Bool mixup, will shut down instead of start bot again if game recovery is sucessfull
> Fix game recovery

- game.ini
- src/bot.py
- src/death_manager.py
- src/game_recovery.py
Otherwise, the game recovery will fail if the save and exit screen is present as it thinks its already at hero selection and exits
> Fix logo found on save and exit screen

- src/pickit.py
- src/run.py
Add last_item.score to item pickup as a % confidence. Suspect this will be useful for support, helping users decide on threshold, etc.
> Item scores

- src/shop/ias_gloves.py
Init should use monitor from param and shop_loop
> Fix javashop monitor

- src/belt_manager.py
- src/health_manager.py
Updates potion count on use as to allow for pickit of pots on current run. Ty @jagarop .
Also added stats for potion drinking
Closes #142
> Update pot count on use

- src/belt_manager.py
I think this was correct before last commit.
> Revert incorrect pot increment

- src/pickit.py
It would not switch back to teleport to move closer to an item and keep telekinesis on.
> Fix item pickup with telekinesis

- README.md
- params.ini
- src/char/i_char.py
- src/config.py
- src/pather.py
Not needed anymore with the pather improvements. I hope :D
> Remove slow walk + adjust node positions

- src/npc_manager.py
Reverts parts of #171 
Sry for the bad review @mgleed. Apart from the issue with the passed argument, I think we have to keep it split because we do gold and white filtering separately.
> Revert npc multi tempalte search

- README.md
- params.ini
- src/config.py
- src/game_stats.py
discord_status_count defines number of games between discord status messages being sent. Defaults to 20
> Added new param discord_status_count

- src/belt_manager.py
- src/bot.py
- src/char/hammerdin.py
- src/char/i_char.py
- src/pather.py
- src/run/__init__.py
- src/run/pindle.py
- src/run/shenk_eld.py
- src/run/trav.py
- src/town/a3.py
- src/ui_manager.py
Some code refactoring to remove logic from bot.py and some minor adjustments to moving and creating tp on trav.
> Refactor runs

- src/char/i_char.py
- src/pather.py
- src/template_finder.py
> Speed up template pathing

- src/bot.py
- src/health_manager.py
- src/run/pindle.py
- src/run/shenk_eld.py
- src/run/trav.py
Have to split up the runs to update the current location in "approach" which will move your toon until out of town in the area of the boss and "battle" where your toon is moving towards the mobs and doing its thing.
> Fix health manager pause

- src/char/hammerdin.py
- src/game_stats.py
- src/pickit.py
- src/run/pindle.py
- src/run/shenk_eld.py
- src/run/trav.py
- src/utils/misc.py
also do some coloring of items. Not sure if it is helpful or just annoying...
> Add area to items found

- config/params.ini
- environment.yml
- src/bot.py
- src/config.py
- src/dclone_ip.py
This is add on to pause the bot and send msg to discord if we are able to obtain the correct hot ip for dclone.
> dclone ip hunting

- src/char/i_char.py
- src/town/a3.py
- src/town/a4.py
- src/town/a5.py
- src/town/town_manager.py
- src/ui/ui_manager.py
- src/version.py
Wants to move to "4th" stash and clicks out of inventory. gets stuck
> Fix stashing

- src/bot.py
- src/game_stats.py
- src/run/pindle.py
- src/run/shenk_eld.py
- src/run/trav.py
Add location from the Run procedure and all Discord messages can levrage
> Add location from the Run procedure

- src/bot.py
- src/game_stats.py
1. Add a merc deaths counter in game_stats.py.
2. Trigger: put it in bot.py while Check if merc needs to be revived.
> Add-Mercenary-deaths-counter

- src/game_stats.py
Logs Items,Deaths,Chickens,Merc Deaths, and Fails for each run
Discord message prints stats by run in table
stats.log lists run table and items by run
> Adding location_stats dict to hold stats for each run

- README.md
- config/params.ini
- src/bot.py
- src/config.py
- src/game_stats.py
- src/run/shenk_eld.py
…d status report
Defaults to 0
> Config discord condensed

- src/ui/ui_manager.py
> tome bug workaround

- src/pather.py
- src/town/a3.py
- src/utils/custom_mouse.py
- test/mocks/screen_mock.py
- test/pather_test.py
- test/smoke_test.py
- Fixes going back to trav when moving from ormus to stash
- Robustify the risk of having the merc inventory open on accident while pathing
> Dont click on merc icon and force_move in a3 town

- README.md
- config/params.ini
- src/bot.py
- src/config.py
this will have you repair at the start of each run.
not recommended for high runewords.
mainly for poor folk with tele necklaces that have charges.
usage:
set 'always_repair=1' in params.ini
> Repair Each Run

- README.md
Update readme with a warning against using botty online.
> Warn against using botty online

- src/pather.py
- src/town/a5.py
> fix for IDing

- src/town/a3.py
Cain can now identify in act 3
> Identify in Act 3

- src/game_controller.py
- src/main.py
- src/utils/auto_settings.py
> Warn user about D2r settings not being as required

- src/bot.py
- src/chest.py
- src/run/arcane.py
This messed up the unittests since the mocked screen is not used there otherwise.
> Take screen as param in Chest Class

- src/game_stats.py
> Updating Beautiful Table Styling

- src/bot.py
- src/game_stats.py
- src/item/pickit.py
- src/ui/ui_manager.py
- test/game_stats_test.py
uiManager now knows game_stats
keep item now logs items pickit
> only log item on keep of item

- src/ui/ui_manager.py
If super potions are not available (e.g. nightmare), buy greater potions.
> Buy greater potions in nightmare

- src/char/sorceress/light_sorc.py
> Update light sorc shenk

- src/api/discord_embeds.py
- src/api/generic_api.py
- src/bot.py
- src/game_controller.py
- src/messenger.py
- src/shop/anya.py
- src/utils/dclone_ip.py
> Revert "Messaging update"

- src/bot.py
- src/char/barbarian.py
- src/char/basic.py
- src/char/basic_ranged.py
- src/char/hammerdin.py
- src/char/i_char.py
- src/char/necro.py
- src/char/sorceress/sorceress.py
- src/char/trapsin.py
- src/config.py
- src/death_manager.py
- src/game_controller.py
- src/health_manager.py
- src/item/item_finder.py
- src/item/pickit.py
- src/main.py
- src/npc_manager.py
- src/shopper.py
- src/town/town_manager.py
- src/ui/char_selector.py
- src/ui/ui_manager.py
- src/utils/graphic_debugger.py
- src/utils/item_extractor.py
- test/item/item_finder_test.py
@hectorgimenez please have a look
> Make config static and global

- src/char/sorceress/blizz_sorc.py
> Nihlathaks no longer count cold immune run as fail

- src/item/item_finder.py
- src/item/pickit.py
Thank you @codahq #485 
Thought to rename `closest_item` since it will now better represent closest desired item, but there are other variable names in there already like `desired_item` etc so I decided to leave it alone.
> prioritize runes/uniques/set items then pick others

- src/chest.py
> stash bugfix

- assets/d2r_settings.json
Will assist with item drop segmentation
> Add controller item spacing to default botty settings file

- src/ui/ui_manager.py
> Bugfix: vendor_stash merging artifact

- src/bot.py
- src/config.py
- src/ui/ui_manager.py
Fix for gambling issue. Looks like self._config.char["gamble_items"] always returns true. Therefore im checking if the first entry is empty and go for a not.
not self._config.char["gamble_items"][0]==""
> gambling bugfix

- src/char/hammerdin.py
Users reported crashes, because optional auras were considered mandatory for CS.
> CS Hammerdin: optional skills now checked for binding before cast

- src/ui/ui_manager.py
This reverts commit 9fe6a8117ea21eed1d4bdeb8bfe936bb884c3f3f.
Currently bugs with chicken. Will plan to reimplement #555 once fix is identified
> Revert: "Speed up save_and_exit (#555)"

- README.md
- src/game_stats.py
Noticed a few typos in the Readme and game_stats.py and corrected them
> corrected typos

- src/bot.py
Sorry I pinged you so late! This should fix the bug with enigma classes being treated as tele ammy users after dying.
> Bugfix: Check capabilities after corpse pickup

- src/char/sorceress/blizz_sorc.py
added missing template finder after ui merge. Required for nihlathak script.
> missing template finder for blizz sorc nihlathak

- src/messages/discord_embeds.py
- src/messages/generic_api.py
Fixes warnings if webhook not set but discord messenger api is param. Unmasked by #569
> Bugfix: Suppress warning if no discord webhook set

- src/screen.py
* Moved core screen functions to the top
* Add find_and_set_window_position call
> Create find_and_set_window_position in screen.py for testing

- config/params.ini
- src/char/i_char.py
- src/config.py
For the folks having problems with autodetection and also the folks who want to use teleport charges without optimization
> Add override_capabilities param to workaround problems with autodetection

- README.md
**Overview**
Improve the documentation of the `[general]` section of the `README.md` to prevent confusion on settings and provide clear documentation.
**Testing**
N/A, simply a readme change.
> Improve the README.md [general] documentation

- src/bot.py
- src/inventory/common.py
- src/inventory/personal.py
- src/inventory/vendor.py
Due to my poorly written try/except statement that needed to have a conditional statement based on the statement succeeding or failing.
> Bugfix: Gold stashing

- src/town/a1.py
- src/town/a3.py
- src/town/a4.py
- src/town/a5.py
Added `force_move=True` to all town traverse_nodes functions. No problems on my end while testing for an hour or so.
> Bugfix: Avoid entering town portals while walking in town

- src/town/town_manager.py
Should solve a lot of "INV_SCROLL_TP not found" and like errors
> Bugfix: Some vendor items obscured by tooltips

- config/params.ini
created note for num loot to avoid confusion. Per Sosa.
> Note for num loot

- README.md
- config/params.ini
- src/config.py
- src/item/item_finder.py
- src/item/pickit.py
- src/run/trav.py
Added ability to use OCR to pickup gold during pickit with a new parameter `min_gold_to_pick` replacing `gold_trav_only`.
> Feature: Use OCR for gold pickit

- src/char/sorceress/light_sorc.py
Adjustments to lightning sorceress attack sequence.
Adjustments cast lightning proceeding chain lightning in loops as discussed with Gleed https://discord.com/channels/904057828791185458/908600901491638282/953731270213521529
> Tweaked light sorc attack sequence

- src/char/sorceress/blizz_sorc.py
added an extra attack sequences and added wait timers.
> Improved eld attack sequence for Blizz sorc

- environment.yml
- src/logger.py
Added colors for the printing. very nice to look at for everyone.
lightblue -logger.info
lightyellow - logger.warning
lightred - logger.error
red - logger.critical
(errors and warning below were forced by me to show off the colors..)
> added logged colors

- src/inventory/belt.py
see this often in the discord, people getting an esoteric error for not setting their belt hotkey in params.ini
> error handling for common belt error

- src/bot.py
- src/game_stats.py
- src/ui/player_bar.py
- src/utils/levels.py
Start of each game and end of each run OCR exp
game_stats stores starting EXP and current EXP
game_stats summary calculates XP gained, XP per game, XP per hour
> Leveraging OCR to read exp and track in game_stats

- README.md
- config/params.ini
- src/bot.py
- src/config.py
- src/game_stats.py
- src/messages/discord_embeds.py
- src/run/shenk_eld.py
Condensed message will be default. removed the option from params.
> Condsensed discord message will be the only option

- src/item/item_cropper.py
Fix item_cropper failure on D2R 2.4
> BugFix: Allow 2 lines of tooltip

- src/char/i_char.py
Is this a newly introduced operator in the latest python versions?
> fix: Remove ;

- src/inventory/common.py
1) 4 tabs instead of 3
2) Return value should be integer when failed
> BugFix: Fix indicator_location_to_tab_count

- src/char/basic.py
- src/char/basic_ranged.py
Basic and range can now buff with CTA as well as use class buffs
> Add CTA to Basic and Range

- src/game_stats.py
> Filter items and discord notifications with new NIP system.

- config/game.ini
- src/char/sorceress/light_sorc.py
Need verification doesnt impact hdin or light sorc.
> Lowered Eldritch End node

- config/params.ini
- src/config.py
- src/game_controller.py
- src/game_stats.py
It can produce a lot of spam for low level bots.
> Make log chicken an option

- src/ui/view.py
Removed unnecessary down key hit which would cause looping upon existing. Added small wait timer before hitting esc.
> Fixing fast exit bug

- README.md
- config/params.ini
- src/bot.py
- src/char/sorceress/__init__.py
- src/char/sorceress/hydra_sorc.py
- src/config.py
Only runs pindle shenk eld so far
> New Hydra Build

- src/char/sorceress/blizz_sorc.py
Speed up nihlathak wait timers to reduce chickens/deaths
> Speed up nihlathak wait to reduce chickens/deaths

- src/shop/anya.py
- src/shop/drognan.py
Leverages `template_finder.search_all()` from #770
> Bugfix: Fix shoppers so multiple items are detected again

- README.md
Added some better text for the contribution message and moved it up next to the development text. You can see a preview on my fork https://github.com/Aimware0/botty
> Updated readme for contributions

- src/char/bone_necro.py
- src/char/i_char.py
- src/char/necro.py
- src/char/poison_necro.py
There is no reason to have 3 copies of the same function. Let's make _lerp a common function for all characters.
> Move _lerp function to i_char.py

- src/town/town_manager.py
- src/ui/view.py
> Bugfix: Reduce identify time at cain

- src/config.py
> Added error handling for missing params inside config files

- config/params.ini
- src/bot.py
- src/config.py
- src/game_controller.py
- src/ui/character_select.py
- src/ui/main_menu.py
- src/utils/restart.py
Added option `online_char` to params.ini.
Will check online tab status before creating games when `online_char` is 1.
> Fix Issue #789: Select online tab before creating game when d2r switch to offline tab automatically

- src/bot.py
- src/game_controller.py
- src/game_stats.py
- src/messages/messenger.py
- src/shop/anya.py
- src/utils/dclone_ip.py
> Bugfix: NoneType messages if api or hook not set

- src/bot.py
- src/ui/character_select.py
> Feature: Debug screenshots for character select failures

- config/default.nip
> Bugfix: Default.nip syntax error

- README.md
- config/params.ini
- src/char/i_char.py
- src/char/paladin/fohdin.py
- src/char/paladin/paladin.py
- src/config.py
Implemented so far only in FOHdin routine, but should be generalizable.
> Feature: safer_routines param for hardcore players, etc

- README.md
- src/game_stats.py
- src/nip/lexer.py
- src/nip/tokens.py
Allows you to specify the specific expressions you want to receive notification for
`@[type] == ring` = no notification
`[type] == ring` = notification
> Nip expression notfications

- src/pather.py
- src/template_finder.py
Used photoshop to help use Eldritch templates for Shenk nodes
> Bugfix: Help botty find Shenk nodes near Eldritch

- src/ui/skills.py
> Revert "Bugfix: give more time for select_tp() for detect capabilities"

- config/default.nip
Corrected Chipped Amethyst
Corrected Bow sockets (Mist Runeword)
Corrected [Quality] issue on base items
Added Cryptic & Mythical Swords (Plague Bases)
Accidently corrected sentence case as well 😅
> Corrections for default.nip

- src/pather.py
- src/ui_manager.py
> Fix: find_nearest_nonzero() NoneType error

- src/ui/view.py
No pickup was turned off permanently by mistake.
> No pickup fix

- src/bot.py
> Fix not stashing gold if buying sth before

- config/default.nip
Corrected white staves and other syntax errors.
> Updated staves and nip errors

- src/template_finder.py
- test/template_finder_test.py
Also updated tests to keep image references in each unittest. Ty @Ezro
> Bugfix: template_finder.search_all() messing with input arguments
