bottytools/botty

- README.md
- params.ini
- src/char/i_char.py
- src/config.py
Adds a new params section, "advanced_options"
Adds a new param to the advanced_options section, "pathing_delay_factor"
The pathing delay factor will allow users to scale the otherwise static delays in the pathing `move` operations based on their own needs.
> add advanced params section with pathing delay

- src/item_finder.py
Otherwise a "Ring Mail" might loose vs just "Ring" because its 0.998 vs 0.997
> Force blackmailed items to have higher score

- src/bot.py
- src/run.py
Fixes the issue where you would die during tp and then not check corpse afterward and run around without gear.
Also, added some death screen checking at end of run and game, so it should not even happen that max game length is reached.
Also now create screenshot when max game length is reached (previously only on when recovery was unsuccessful).
Also do not reset game stats anymore if game recovery is called.
> Check corpse after game recovery

- src/bot.py
- src/ui_manager.py
For now it is every 3rd run (eld and shenk count as 1 run!).
Otherwise, with a strict pickit and few stash columns in inventory you can get in a situation where you pick up unwanted stuff and your inventory is full and you can not pick up desired loot anymore.
> Check if stashing is needed on start after x runs without stashing

- src/ui_manager.py
- src/utils/custom_mouse.py
When checking if we want to discard an item we check if there really is an item at that current location. If the screenshot includes the cursor this check returns true. By discarding an item that is not there we cancel the stash screen and everything goes down the toilet from there...
We get stuck, we think the stash tab is full...
> Fix getting stuck at discarding

- src/char/sorceress.py
- src/death_manager.py
- src/health_manager.py
Small change to keep the mouse held down during this attack delay, seems to speed up the attack sequence by a few frames and I haven't had any issues in my testing.
> fix(sorc): hold mouse during attack delay

- src/health_manager.py
Ran into a mana burn champ and had all 8 full rejuvs drained within 2 seconds. 
```
[2021-11-30 22:02:25,394] DEBUG      Waiting for Template ['ELDRITCH_0', 'ELDRITCH_START']
[2021-11-30 22:02:38,542] DEBUG      Drink rejuv potion in slot 2. HP: 97.9%, Mana: 0.0%
[2021-11-30 22:02:38,676] DEBUG      Drink rejuv potion in slot 2. HP: 97.9%, Mana: 0.0%
[2021-11-30 22:02:38,816] DEBUG      Drink rejuv potion in slot 2. HP: 97.9%, Mana: 0.0%
[2021-11-30 22:02:39,106] DEBUG      Took a screenshot of current loot
[2021-11-30 22:02:39,457] DEBUG      Drink rejuv potion in slot 2. HP: 96.7%, Mana: 0.0%
[2021-11-30 22:02:39,600] DEBUG      Drink rejuv potion in slot 4. HP: 96.7%, Mana: 0.0%
[2021-11-30 22:02:39,735] DEBUG      Drink rejuv potion in slot 4. HP: 96.7%, Mana: 0.0%
[2021-11-30 …
```
> Fix rapid-fire rejuvs edge case

- src/game_stats.py
- src/run.py
After max game length is reached the timer is not reset, only when start_game is called. Then two Bot() instances are started.
> Fix gamerecovery creating 2 bot instances

- README.md
- params.ini
- src/config.py
- src/utils/auto_settings.py
This helps me whenever I have to re-run the auto-settings, since my default folder is different than the one that this bot uses:
`C:\Users\cesar\Saved Games\Diablo II Resurrected` -> my saved games folder
`C:\\Users\\cesar-local\\Saved Games\\Diablo II Resurrected` -> botty's default saved games folder
`os.getlogin()` differs from my user folder. I'm not sure why this happens, so I came up with this implementation under the **[general]** settings in `params.ini`.
> Add saved_games_folder param

- src/death_manager.py
- src/game_stats.py
- src/health_manager.py
Forgot to remove a delay in chicken that was used to test the situation when chicken wants to execute but meanwhile your char dies.
Also fixes a bug that self._timer is None when you die on end_game()
> Fix creash on death and chicken delay

- src/pickit.py
Quite a bit hacky... timer will check if we try to pick up the same item over and over again. After 4 sec it will try to force a move (with teleport this can fix the issue), after another 4 sec it will skip this item type for this round.
> Fix item pickup behind obstacles

- src/config.py
Currently getting a runtime error when there is an item config in the pickit set to 1 which does not have an asset.
Should just print the warning an proceed as normal.
> Fix config error

- src/char/sorceress/blizz_sorc.py
- src/char/sorceress/light_sorc.py
I was getting a crash when trying A2 summoner with my blizz sorc, looks like the right_attack and left_attack methods are only defined on Trapsin class and not for the Sorceress base class used by light and blizz ones.
I replaced the calls by the same strategy used for pindleskin and it works, probably not the best one but working and not crashing.
> Fix for crash on A2 Summoner for Sorceress

- src/run/arcane.py
Instead of just applying pre-buff once at the start of the whole Arcane Sanctuary, it now applies it before checking each "arm" of the map.
> Pre-Buff before each arm - if do_pre_buff is enabled.

- config/params.ini
- src/config.py
- src/screen.py
- src/utils/misc.py
Currently to initialize Screen object we need to start with character selection page (or hack it). This is problematic when I want to have a faster feedback loop on testing changes. E.g. not restarting the game when testing out some pathing tweaks. Having Screen object being able to initialize any time we can write tests that navigate the bot mid game and just execute them via 
```
python test/test_name.py
```
Those tests are quite easy to do and I was able to repurpose smoke_test.py to use a real screen instead of mock screen and test scenario over and over without closing the game
Win32 API allows cycling through the opened window and get the process that running them. This in turn allows getting ClientRect of the window without window border. Which is pretty much what old code did. 
1. …
> Find D2R window using win32api instead of pattern matching

- README.md
- config/params.ini
- src/char/hammerdin.py
- src/config.py
- src/ui/ui_manager.py
Added an option fill_shared_stash_first to params.ini
When true, it will stash loot starting from the rightmost stash tab going left (personal tab last). That way dead HC characters can still at least recover the loot they found during their last session.
> Add option to fill shared stash tabs first (useful for HC characters)

- src/api/discord_embeds.py
- src/game_stats.py
When the generic_api is in use, the bot name appears twice at the start of each status update message, because the bot name is added at the start by both the GameStats `_send_status_update` method and the GenericApi `_send` method.
example of bug:
This commit changes the behavior of the _send_status_update method. If the generic_api is in use, it will avoid adding the bot name to the start of the message.
> fix duplicate bot name in status update message

- src/screen.py
- src/utils/misc.py
- `find_window_via_win32_api=1` option only works with a single monitor setup, changes enables supporting multiple monitors
- Cleaning up some trailing whitespaces in screen.py
> Support multiple monitors with win32api

- src/char/sorceress/light_sorc.py
The line below doesn't always succeeds (could be due to a pack of mobs blocking the view) and botty just exits the game in this case which leads to failed run. I would've failed ~25 runs out of 145 last night if I didn't have this fix
```python
self._pather.find_abs_node_pos(end_nodes[-1], self._screen.grab())
```
Blizzard sorc also doesn't exits in case above returns None and just carries on. I've opted to cast static to get some potential value and add a wait before trying again
Attaching logs from last night
[logs.txt](https://github.com/aeon0/botty/files/7965270/logs.txt)
> Fix Lightning Sorc Sometimes Exits in the middle of Nihlathak fight

- src/char/i_char.py
Most likely a merge issue as it was fixed at some point throughout 
#476
For some reason
```python
self._ui_manager.is_right_skill_selected(["TELE_ACTIVE"])
```
is returning true when Teleport is inactive in town.
> Fix character stuck trying to teleport in town

- src/messages/discord_embeds.py
- src/messages/generic_api.py
Last week when Discord's servers were down, I discovered that there were uncaught exceptions being thrown in the Discord API logic that caused Botty to crash, I was botting on a Hardcore character at the time, and this left my character standing in-game at the Waypoint without Botty running (no chicken). This could cause a Hardcore death.
This PR added exception handling to the Discord API calls that have the potential to throw exceptions, possibly preventing unnecessary deaths in the event of a Discord outage or Discord Webhook configuration errors.
> Added exception handling to Discord API calls

- src/bot.py
- src/utils/restart.py
1) game isn't being tracked up until start_from_town which means max_game_length_s isn't accounted for during character selection
2) restart_game utility isn't handling new screen behavior properly and depending on it to wait for main menu while it's not
> Fix game isn't restarted when in main menu / character selection screen

- src/utils/graphic_debugger.py
GraphicDebuggerController constructor no longer takes any arguments
> Fix running graphic_debugger.py as a standalone process

- src/char/barbarian.py
This should fix a bug reported with barbarian crashing during run
**Note:** can't test this myself but should be the way
> Fix barbarian crashing on pre_move()

- src/transmute/transmute.py
If cube isn't empty transmute would do god knows what. So checking fist the cube before picking gems. Trying to check the cube only when we know that there are gems to transmute.
> Skip Transmuting if Cube isn't empty

- src/char/i_char.py
Must've been a merge bug. But this fixes botty crashing after death and trying to remap teleport action
> Fix remap keybind is crashing

- src/bot.py
- src/game_stats.py
While the initial code was more resilient, this approach aims to:
* Reduce visual noise (if you're watching the bot)
* Reduce possible behavioral pattern detection
> Track nopickup status in GameStats and only /nopickup once

- src/char/basic.py
- src/char/hammerdin.py
The offset is actually required in both cases (tele or walking) as the point is to get closer to shenk
I've also forced using tp as normally pre_move is responsible for that but we want to keep the concentraction up if we move on teleporting character
Additionally enabled tp_charges on shenk and eldrich routes to take advantage
Tested:
- Hammerdin with enigma
- Hammerdin walking
- Hammerdin walking with charges
> Fix incorrect path offset for shenk. Optimize tele charges

- src/screen.py
- src/ui_components/view.py
Fix bug where save/exit routine would pass an empty template match
```
File "C:\Users\Botty\code\botty\src\bot.py", line 369, in on_end_game
view.save_and_exit()
File "C:\Users\Botty\code\botty\src\ui_components\view.py", line 63, in save_and_exit
if click_save_exit(exit_button):
File "C:\Users\Botty\code\botty\src\ui_components\view.py", line 47, in click_save_exit
select_screen_object_match(match, delay_factor=(0.1, 0.3))
File "C:\Users\Botty\code\botty\src\ui\ui_manager.py", line 202, in select_screen_object_match
mouse.move(*convert_screen_to_monitor(match.center), delay_factor=delay_factor)
File "C:\Users\Botty\code\botty\src\screen.py", line 25, in convert_screen_to_monitor
x = screen_coord[0] + monitor_roi["left"]
TypeError: 'NoneType' object is not subscriptable
```
> Bugfix: Save/exit error

- src/char/i_char.py
Should fix problems with `_remap_skill_hotkey`, whatever they might be.
> Bugfix: Missing import for i_char

- src/item/item_cropper.py
Adjust item_cropper.crop_item_descr. Now properly detects cases where there is a lot of text in the box; e.g.,
> Bugfix: crop_item_descr failing on some items

- .github/workflows/ci.yml
- codecov.yml
- src/__init__.py
Removing the codecov reporting since it is bound to my account and might cause some issues or at least is not nice to the eye to have a few red x on the PR :)
Leaving the coverage report generation just to keep that info available for anybody interested.
> Remove: Codecov

- src/config.py
I had to record & slow down a video to see the error message since the cli closed so quickly due to a missing section header in the custom.ini. this fix it..
> added error handling for custom.ini when missing section header

- src/inventory/personal.py
- src/inventory/stash.py
- src/inventory/vendor.py
- src/transmute/transmute.py
Changed curr_stash dict variable in stash.py to be a global with getter and setter. I believe this manifested as excessively frequent gambling and gold stashing. I think the curr_stash dict wasn't properly updating. Testing overnight to make sure it correctly fixes.
Got rid of old `move_to_stash_tab()` function as it was made obsolete by `common.select_tab()`
Eventually found all I probably really needed all along was in [779b548](https://github.com/aeon0/botty/pull/646/commits/779b54824cbbbd827c52b96e6de96d349d5b7546) but I think the other changes are reasonable.
> Bugfix: Stash tab counts not tracking

- src/inventory/common.py
- src/inventory/personal.py
- src/town/town_manager.py
- src/ui_manager.py
- src/utils/misc.py
Instead of a fixed wait time with multiple attempts to determine whether an item has been transferred successfully; I've implemented a function which waits for an update in a particular screen region.
Should hopefully reduce errors like:
```
[0.7.2 2022-03-29 17:32:55,352] ERROR      transfer_items: could not stash in position (1454, 543)
[0.7.2 2022-03-29 17:32:55,463] DEBUG      Wanted to stash item, but it's still in inventory. Assumes full stash. Move to next.
```
Gives a nice speed boost to low-latency and high-end setups.
Moved transfer_items() from common.py to personal.py since the function is only used from right to left transactions.
> Enhancement/bugfix: Refactor checks for item transferring

- src/game_stats.py
- src/ui/player_bar.py
Numerous xp ocr issues from ocr finding some random character before the experience word. This will ensure those are dropped from the list and it starts with experience as expected.
> Quick list manipulation to remove anything before experience in the list

- src/game_stats.py
Setting starting xp to 1 should alleviate any divide by zero issues. It should never get back to 0.
> Divide by zero fix

- src/inventory/personal.py
Depending on the item attribute hover size it can block out the [X] used to exit inventory leading to being stuck in inventory loop every game.
Solved this bug by checking to see if X button is not visible, if it's not visible it'll center the mouse on screen to get rid of item tooltip. Then will close window.
> Bugfix: Item tooltip obscuring close button

- src/utils/restart.py
Kill the BlizzardError.exe process before restarting the game.
If the game quits due to an error, a BlizzardError window will appear and it will cause botty to restart the game and then fail to select the game window properly.
This is my first pull requests, so please forgive me if there is something wrong.
> Kill BlizzardError.exe

- src/inventory/common.py
- src/inventory/personal.py
Fixes a bug introduced in 7.2 after attempting to fix another bug. 
The current bug manifests with users having their botty quit after attempting to stash/sell/drop an item whose tooltip was too large causing calc_roi() to fail. Calc_roi will still fail with this bugfix, but now anytime an item is to be transferred it will first make sure that inventory slot is not empty. If it is empty, that item will be skipped.
Here is an example of Herald of Zakarum stashing and not causing game to quit when it previously did.
While fixing calc_roi would be nice, this should hopefully no longer be a necessary function with implementation of HoveredItem from d2r_image library by @Ezro, hoping to have 0.8.0 out soon.
> Bugfix: False empty stash tabs due to item tooltip

- config/params.ini
Deletes default `launch_options` param config so botty won't attempt to use mod files for planned upcoming stable release. Will set default `launch_options` again once mods are needed for OCR pickit release.
> Disable mods for planned upcoming stable release

- src/ui/view.py
Discord Bug Report 3:
> Some users experience a loop of save/exit after interacting with cain. The issue seems most common with latency issues or on VM's. The causative function is return_to_play() in view.py. A fix will require adjusting the logic of that function. Current workaround is to use an ID tome in your inventory.
Here I've increased the time limit on return_to_play() from 5 seconds to 8 seconds and then increased the wait time before checking templates again.
I've tested on my character (I'm US East) on Asia server. No loop with Cain. Not sure if this will solve for all users or not. Ideal solution will probably require better logic than current implementation.
> Bugfix: Cain loop, etc. with return_to_play() function

- src/logger.py
Most text editors do not like ANSI color codes
> BugFix: Do not write ANSI color codes to info.log

- README.md
- config/params.ini
- src/bot.py
- src/char/bone_necro.py
- src/char/i_char.py
- src/config.py
- src/utils/misc.py
Added an implementation for bone_necro with support for all runs except Chaos. 
Added cast_in_arc to i_char.py, which is heavily used by the bone_necro implementation. This function allows a skill to be cast more realistically and with reduced downtime.  The mouse is held down for some duration, and moved around while held in order to continue casting randomly within an arc (degrees is a parameter).  
This means that we cast at max speed as opposed to many other implementation in this project where there are additional delays between casts - Usually a cast, then a delay, mouse movement (with it's own delay), another delay, then another cast. 
The only downside to this approach previously, was that if the cast started on an enemy and that enemy died, the skill would stop casting for the …
> Bone necro

- src/pather.py
"Random guess" is always towards bottom when blocked.
> Bugfix: Random guess should be random

- src/messages/generic_api.py
In generic_api.py, custom_loot_message_hook was not supported. I fixed it and it works fine now. If custom_loot_message_hook isn't set in params.ini, use custom_message_hook instead.
> Fix generic_api

- src/char/hammerdin.py
Walking Paladins at Pindle often get charged.
Using an Amulet with Telecharges can provide safety & accuracy.
Pindle Script was adapted for Hdin to teleport the last traverse to [104] (Pindle_end) in case a teleport charges (or native teleport) is available.
> Hdin pindle tele charges

- config/game.ini
problem is due to slight variations in vertical spacing between character name and level depending on how far you are scrolled on CSS. Fixed by taking a smaller crop of the saved character template which captures only the character name.
> Bugfix: Character select screen, character not found

- src/char/paladin/fohdin.py
- src/char/paladin/hammerdin.py
- src/char/paladin/paladin.py
This is ghetto workaround--a tempfix while char overhaul #862 is being worked on. Closes #757, #749 . Ty @drallcom3 for your earlier work. Tested on walking, charged tp, and native TP hammerdin and FOHdins.
> Bugfix: Hammerdin and FOHdin small fixes, inappropriate vigor casting, etc

- src/char/paladin/fohdin.py
- src/char/paladin/hammerdin.py
I made a mistake and increased the timeout duration on trav runs for some nodes. This leads to getting attacked by council without retaliation for longer periods. Reverted that change here.
> Revert: paladin timeout on trav

- src/nip/actions.py
Addresses the following. I believe it stems from an item that isn't gold being fuzzy-matched to gold but having no "amount" property.
```
[0.7.4-dev 2022-06-16 14:48:05,685] DEBUG      fuzzy_base_item_match: change SOLD -> GOLD (similarity: 75.0%)
[0.7.4-dev 2022-06-16 14:48:05,687] DEBUG      Read 7 ground items in 0.407 seconds
Exception in thread Thread-7 (start):
Traceback (most recent call last):
File "C:\Users\aliig\miniconda3\envs\botty\lib\threading.py", line 1016, in _bootstrap_inner
self.run()
File "C:\Users\aliig\miniconda3\envs\botty\lib\threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\aliig\Desktop\bot\botty\src\bot.py", line 163, in start
self.trigger_or_stop('init')
File "C:\Users\aliig\Desktop\bot\botty\src\bot.py", line 183, in …
```
> Bugfix: Handle base item miscorrecting an item to Gold

- src/config.py
On starting botty, it will check to make sure the value for d2r_path is valid before launching.
Example of invalid input:
```
[0.8.0-dev 2022-06-17 15:49:08,857] DEBUG      Loading config
Traceback (most recent call last):
File "C:\Users\aliig\Desktop\bot\botty\src\main.py", line 7, in <module>
import screen
File "C:\Users\aliig\Desktop\bot\botty\src\screen.py", line 21, in <module>
title_regex=Config().advanced_options["hwnd_window_title"],
File "C:\Users\aliig\Desktop\bot\botty\src\config.py", line 53, in __new__
cls._instance.load_data()
File "C:\Users\aliig\Desktop\bot\botty\src\config.py", line 149, in load_data
raise ValueError(f"d2r_path {self.general['d2r_path']} does not exist, please review your params.ini settings and set to your true D2R installation directory")
ValueError: …
```
> Enhancement: Ensure d2r_path exists before starting Botty

- src/item/pickit.py
Solves the following:
```
File "C:\Users\aliig\Desktop\bot\botty\src\run\shenk_eld.py", line 53, in battle
picked_up_items = self._pickit.pick_up_items(self._char)
File "C:\Users\aliig\Desktop\bot\botty\src\item\pickit.py", line 153, in pick_up_items
item = items[item_count]
IndexError: list index out of range
```
> Bugfix: Pickit IndexError

- src/run/diablo.py
I watched 10 hours of diablo run by 4 fohdins. About 30% were failed games which aborted in middle run, especially on detecting that if the seal is openned.  In almost every fail caused by this reason, the seal was openned successfully, but the decisions were closed for 5 times then the game was aborted. 
By increasing the numbers of try and reduce the seal_opentemplates threshold to 0.7, the incorrect judgements on seal's open status seldom occur. Now the ratio of failed games typically reduced. It is about 12% mostly caused by temporary high latency or getting lost after teleport to pick item.
> Update diablo.py _sealdance()

- test/template_finder_test.py
Reorganized template_finder tests
> Fix: template_finder.search() tests were terminating after first "assert"
